---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: http-dep
  labels:
    author: ch
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: http-pod
      labels:
        type: webserver
    spec:
      containers: 
        - name: myhttp
          image: httpd 
