---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
     type: appserver
spec:
  containers:
    - name: mytom
      image: tomee
      resources:
        requests:
          memory: "64Mi"
          cpu: "230m"
        limits:
          memory: "125Mi"
          cpu: "500m"
