---
apiVersion: v1
kind: Pod
metadata:
  name: post-pod
  labels:
    type: db
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: ch1
        - name: POSTGRES_USERNAME
          value: myuser
        - name: POSTGRES_DB
          value: db
