---
apiVersion: v1
kind: Pod
metadata:  
 name: cicd-pods
 labels:
   type: cicd
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
