apiVersion: v1
kind: Pod
metadata:
  name: http-pod
  labels:
    type: appserver
    author: ch
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
