---
apiVersion: v1
kind: ReplicationController
metadata:
  name: http-rc
  labels:
    type: webserver
spec:
  replicas: 2
  template:
    metadata:
      name: http-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttp
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080

