---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pass
  labels:
    type: db
spec:
  containers:
    - name: mysql11
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: a
