---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-dep
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: post-pod
      labels:
        type: db
    spec:
      containers:
        - name: post5
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-sec
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: post-sec
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: post-sec
                  key: dbname




