apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: post-app
  name: post-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/ubuntu-default: "true"
        io.kompose.service: post-app
    spec:
      containers:
        - env:
            - name: POSTGERS_USER
              value: myu
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_PASSWORD
              value: ch3
          image: postgres
          name: post-app
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
