apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-app
  name: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/ubuntu-default: "true"
        io.kompose.service: redis-app
    spec:
      containers:
        - image: redis
          name: redis-app
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
