---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tom-rs
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: tom-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: mytom
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 8080
