---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-dep
  labels:
    type: result-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: result-app
  template:
    metadata:
      name: result-app-pod
      labels:
        type: result-app
    spec:
      containers:
        - name: myresultapp
          image: dockersamples/examplevotingapp_result


