---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-dev
  labels:
    type: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tom-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytom
          image: tomee
      tolerations:
        - key: slave1
          operator: Equal
          value: ch2
          effect: NoSchedule

#tolerancy is used to alredy tainted nodes to allows to run pods
Tolerations "allow the scheduler to schedule pods with matching taints".
--> kubectl apply -f tolerancy1.yml
--> kubectl get all
--> kubectl get pods -o wide #shows which slave taintes thats slave in runs toleration runs pods
