---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-dep
  labels:
    type: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      type: voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        type: voting-app
    spec:
      containers:
        - name: myvotingapp
          image: dockersamples/examplevotingapp_vote
...

#its used to create voting app "deployment" docker image dockersamples/examolevotingapp_vote
---> kubectl apply -f voting-app-dep.yml 
---> kubectl get pods
