---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-dep
  labels:
    type: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        type: worker-app
    spec:
      containers:
        - name: myworkerapp
          image: dockersamples/examplevotingapp_worker

#its voting app creation in the file of "deployment" image copy in docker hub
---> kubectl apply -f worker-app-dep.yml
---> kubectl get pods | less
---> kubectl delete -f worker-app-dep.yml
